services:
  auth:
    restart: always
    build:
      context: .
      target: dev-stage
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
    links:
      - redis
      - mongo

  mongo:
    restart: always
    image: mongo:latest
    ports:
      - '27017:27017'

  redis:
    restart: always
    image: redis:latest
    ports:
      - '6379:6379'

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'